CodeSystem: LabUnitsCS
Id: lab-units-cs
Title: "Laboratory source system units of measure"
Description: "Units of measure as they are sent verbatim by laboratory information systems in Uzbekistan. This code system mirrors the source data, including spellings that are not valid UCUM, so that incoming results can be received, mapped to UCUM (see LabUnitsToUCUMCM) and progressively corrected at source. It is not a code system to author against: new laboratory results must carry UCUM in Observation.valueQuantity."
* insert OriginalCodeSystemDraft(lab-units-cs)

// Case sensitive: the source system distinguishes ml from Ml, pH from PH and Me/l from me/l.

* #"mcg/dl" "mcg/dl"
* #"10^12/L" "10^12/L"
* #"mmol/l" "mmol/l"
* #"mlU/mL" "mlU/mL"
* #"yr" "yr"
* #"KP" "KP"
* #"nmol/l" "nmol/l"
* #"Копий/10^5 клеток" "Копий/10^5 клеток"
// Not a unit of measure
* #"№" "№"
* #"min" "min"
* #"Mcg/ml" "Mcg/ml"
* #"g/l" "g/l"
* #"mg/%" "mg/%"
* #"EIU" "EIU"
* #"mkl" "mkl"
* #"ug/dL" "ug/dL"
* #"sec" "sec"
* #"mg/l" "mg/l"
* #"п/з" "п/з"
* #"Mcg/l" "Mcg/l"
* #"mkmol/l" "mkmol/l"
* #"yed/ml" "yed/ml"
* #"mmol/L" "mmol/L"
* #"минут" "минут"
* #"me/l" "me/l"
// Parses as microlitre per millilitre, which is not a plausible lab unit. Most likely uU/mL or U/mL - pending clarification from the source system
* #"ul/ml" "ul/ml"
* #"U/ml" "U/ml"
* #"IU/ml" "IU/ml"
* #"yed/l" "yed/l"
* #"IU/L" "IU/L"
* #"в п/зр" "в п/зр"
* #"AU/ml" "AU/ml"
// Rh factor is a qualitative attribute, not a unit
* #"RH" "RH"
* #"µmol/l" "µmol/l"
* #"MYe/ml" "MYe/ml"
* #"mlU/ml" "mlU/ml"
* #"Me/l" "Me/l"
* #"pmol/L" "pmol/L"
* #"GE/ml" "GE/ml"
// Parses as minute per percent; not a coherent unit - source data error
* #"min/%" "min/%"
* #"pg/ml" "pg/ml"
* #"pg" "pg"
* #"mmol/d" "mmol/d"
* #"Mmol/D" "Mmol/D"
* #"sek" "sek"
* #"mkg/ml" "mkg/ml"
* #"Ml" "Ml"
* #"day" "day"
* #"ml" "ml"
// Semi-quantitative result, not a unit: send as Observation.valueCodeableConcept
* #"+" "+"
* #"µmol/L" "µmol/L"
// Data type marker, not a unit: send as Observation.valueString
* #"text" "text"
* #"10^3/ml" "10^3/ml"
* #"fL" "fL"
// Parses as milligram per second, but mg/s in the source is most likely mg/sutki (mg/d). An 86400x error either way - pending clarification
* #"mg/s" "mg/s"
* #"mg/L" "mg/L"
* #"ng/mL" "ng/mL"
* #"mm/h" "mm/h"
* #"G/L" "G/L"
* #"pH" "pH"
* #"mg/dL" "mg/dL"
* #"Mk ME/ml" "Mk ME/ml"
// Meaning unclear - pending clarification from the source system
* #"Nm/mg" "Nm/mg"
* #"nmol/L" "nmol/L"
* #"ng/dl" "ng/dl"
* #"ml%" "ml%"
* #"mkg/l" "mkg/l"
* #"U/L" "U/L"
* #"mIU/mL" "mIU/mL"
* #"10^9/L" "10^9/L"
* #"μg/dL" "μg/dL"
// Semi-quantitative result, not a unit: send as Observation.valueCodeableConcept
* #"+/-" "+/-"
* #"Klet./mkl" "Klet./mkl"
* #"ug/dl" "ug/dl"
* #"mIU/ml" "mIU/ml"
* #"мкл" "мкл"
// Not a unit of measure
* #"," ","
* #"Me/ml" "Me/ml"
// Not a unit of measure
* #"." "."
* #"ratio" "ratio"
* #"pg/mL" "pg/mL"
* #"ng/ml" "ng/ml"
* #"mmol/h" "mmol/h"
* #"mkmol/L" "mkmol/L"
* #"IU/mL" "IU/mL"
// Meaning unclear - pending clarification from the source system
* #"U/e" "U/e"
// Meaning unclear - pending clarification from the source system
* #"E/m" "E/m"
* #"cm" "cm"
* #"uU/ml" "uU/ml"
* #"Mg/l" "Mg/l"
* #"%" "%"
* #"в п/з" "в п/з"
* #"number" "number"
* #"ml/min" "ml/min"
* #"ME/ml" "ME/ml"
// Ambiguous: mL/min or mL per m2 of body surface area - pending clarification
* #"ml/m" "ml/m"
* #"mIU/L" "mIU/L"
* #"Mmol/L" "Mmol/L"
* #"U" "U"
* #"f/l" "f/l"
* #"PH" "PH"
* #"сек" "сек"
* #"AU/mL" "AU/mL"
* #"У. е." "У. е."
* #"S/CO" "S/CO"
* #"mME/ml" "mME/ml"
* #"10^g/L" "10^g/L"
* #"OP" "OP"
* #"lg" "lg"
* #"на 100 лейк." "на 100 лейк."
* #"10*9/L" "10*9/L"
* #"Ng/ml" "Ng/ml"
* #"mmol/sperm" "mmol/sperm"
